# =============================================================================
# De Novo Sequence Designer — Native Full Differentiable / DDP-Ready
# SUPER DNS ONE Cluster / ONE Ecosystem
# =============================================================================
# Developer    : PAI, Yoon A Limsuwan / MSPS NETWORK
#                MY SOUL MOVE BY POWER OF HOLY SPIRIT
# ORCID        : 0009-0008-2374-0788
# GitHub       : yoonalimsuwan
# Contact      : msps4u@gmail.com
# License      : MIT
# Year         : 2026
# Version      : 2.0.0 (Production / AMP-Safe / torch.compile-Ready)
# =============================================================================
"""
Production-grade, fully differentiable De Novo Sequence Designer.

Fixes and improvements over the v1.0.0 reference
-----------------------------------------------
1. **DDP batch-collapse bug fixed — the viability score was a single scalar
   for the entire world batch.**  The reference wrote

       viability_score = torch.sigmoid(log_det.mean(dim=-1, keepdim=True))

   where `log_det` has shape `[B]` (batched `slogdet` output).  `.mean(dim=-1)`
   reduces over the **batch** dim, producing a `[1]` tensor and silently
   averaging every sample on every DDP rank — the classifier signal becomes
   identical for every sample and DDP gradients lose their per-sample routing.
   The fix produces a genuine per-sample score `[B, 1]`.

2. **Matrix-dimension bug fixed for `seq_length != hidden_dim`.**
   The reference built `reg_matrix = M_A @ M_A^T + eye(hidden_dim) * 1e-4`,
   where `M_A` is `[B, seq_length, hidden_dim]`, so `M_A @ M_A^T` is
   `[B, seq_length, seq_length]`.  Broadcasting a `[H, H]` identity against a
   `[B, L, L]` tensor crashes for `L != H`.  The identity now matches the
   Gram-matrix dimension `L = seq_length` exactly, so the module runs for any
   combination of `seq_length` and `hidden_dim`.

3. **`slogdet` → Cholesky for the SPD log-determinant.**  `M_A M_Aᵀ + λI` is
   symmetric positive-definite by construction.  The canonical
   `log det = 2 · Σ log(diag(L))` after `torch.linalg.cholesky` is faster,
   more stable, and does not need to inspect the sign of the determinant.
   Cholesky is computed in fp32 and cast back, so it is safe under AMP.

4. **Numerically sane viability scale.**  Raw `sigmoid(log_det)` saturates
   for any realistic matrix size (log-det grows ~`L·log(σ²)`), giving zero
   gradients from the first step.  Viability is now
   `sigmoid(log_det / L)` — the *mean* log-eigenvalue of the Gram matrix —
   which stays in the informative range for typical data.

5. **Per-forward allocation removed.**  `torch.eye(hidden_dim)` was allocated
   inside every `forward` call (a `torch.compile` recompile trigger and an
   extra GPU allocation).  The identity is now a non-persistent buffer that
   follows the module's dtype/device.

6. **Deterministic inference (optional, on by default).**
   `F.gumbel_softmax` samples noise in both train and eval.  The new module
   adds `deterministic_eval=True`: in `.eval()` the sequence is generated by
   `argmax` of `softmax(logits/τ)` with a straight-through estimator, giving
   a reproducible forward pass.  Set to `False` for the reference's
   always-stochastic behaviour.

7. **Disordered-noise gate.**  `torch.randn_like(sampled_seq)` is now gated on
   `self.training` — no random noise injected during evaluation.

8. **Sane sequence-logits initialization.**  `nn.init.orthogonal_` on a
   `[1, L, V]` tensor flattens to `[1, L·V]` and produces a near-zero
   (unit-norm) initialization, not the orthonormal `[L, V]` matrix it looks
   like.  Replaced with `normal_(std=0.02)` — the standard small-variance
   initialization for token logits.

9. **AMP-safe.**  All internal math that can lose precision in fp16 / bf16
   (Cholesky, log of eigenvalues, sigmoid of large values) runs in fp32 and
   casts back.

10. **`torch.compile`-stable.**  No Python scalars in the hot path, no
    data-dependent control flow, no per-forward allocations.

11. **Backward-compatible public API.**  Same class name, same positional
    constructor signature `(seq_length, vocab_size, hidden_dim)`, same forward
    signature `(batch_size, temperature, noise_scale)`, same returned dict
    keys — a strict drop-in upgrade.

Multi-GPU (DDP) usage
---------------------
    torch.backends.cudnn.benchmark = True
    torch.backends.cuda.matmul.allow_tf32 = True
    designer = DifferentiableStructuralDesigner(seq_length=200).to(rank)
    designer = torch.compile(designer, mode="max-autotune")            # optional
    designer = torch.nn.parallel.DistributedDataParallel(
        designer, device_ids=[rank], gradient_as_bucket_view=True,
    )
    with torch.amp.autocast(device_type="cuda", dtype=torch.bfloat16):
        out = designer(batch_size=32)
    loss = -out["viability_score"].float().mean()
    loss.backward()
"""

from __future__ import annotations

import math
from typing import Dict, Optional, Union

import torch
import torch.nn as nn
import torch.nn.functional as F

__all__ = ["DifferentiableStructuralDesigner"]


# =============================================================================
# Module
# =============================================================================
class DifferentiableStructuralDesigner(nn.Module):
    """
    Highly optimized Structural-Calculus sequence designer with strict
    polynomial-time complexity and full backpropagation.

    Parameters
    ----------
    seq_length : int
        Length of the generated polypeptide chain (positive).
    vocab_size : int
        Amino-acid vocabulary size (default 20 canonical AAs).
    hidden_dim : int
        Width of the structural-feature space (default 128).
    reg_lambda : float
        Tikhonov regularization added to the Gram matrix to guarantee SPD.
    viability_scale : float, optional
        Divisor applied to the log-determinant before sigmoid.  Defaults to
        `seq_length` (mean log-eigenvalue interpretation).
    deterministic_eval : bool
        If `True` (default), `.eval()` uses a deterministic argmax STE.
        If `False`, `.eval()` uses `F.gumbel_softmax` (stochastic).
    gradient_checkpointing : bool
        Recompute the step during backward — trades ~2× compute for activation
        memory savings in long chains / large batches.
    validate_inputs : bool
        Cheap shape guards. Disable once shapes are statically known to avoid
        `torch.compile` recompiles.
    """

    def __init__(
        self,
        seq_length: int,
        vocab_size: int = 20,
        hidden_dim: int = 128,
        *,
        reg_lambda: float = 1e-4,
        viability_scale: Optional[float] = None,
        deterministic_eval: bool = True,
        gradient_checkpointing: bool = False,
        validate_inputs: bool = True,
    ) -> None:
        super().__init__()

        if not (isinstance(seq_length, int) and seq_length > 0):
            raise ValueError("seq_length must be a positive int.")
        if not (isinstance(vocab_size, int) and vocab_size > 0):
            raise ValueError("vocab_size must be a positive int.")
        if not (isinstance(hidden_dim, int) and hidden_dim > 0):
            raise ValueError("hidden_dim must be a positive int.")
        if not (math.isfinite(reg_lambda) and reg_lambda > 0.0):
            raise ValueError("reg_lambda must be > 0.")
        if viability_scale is not None and not (
            math.isfinite(viability_scale) and viability_scale > 0.0
        ):
            raise ValueError("viability_scale must be > 0.")

        self.seq_length = int(seq_length)
        self.vocab_size = int(vocab_size)
        self.hidden_dim = int(hidden_dim)
        self.deterministic_eval = bool(deterministic_eval)
        self.gradient_checkpointing = bool(gradient_checkpointing)
        self.validate_inputs = bool(validate_inputs)

        # ---- Learnable sequence logits (small-variance init) ---------------
        #   The reference's `nn.init.orthogonal_` on a `[1, L, V]` tensor
        #   flattens to `[1, L·V]` and produces a unit-norm vector, not the
        #   orthonormal `[L, V]` matrix it appears to intend.  Standard token
        #   logits use a small normal init.
        self.seq_logits = nn.Parameter(torch.empty(1, self.seq_length, self.vocab_size))
        nn.init.normal_(self.seq_logits, std=0.02)

        # ---- Structural Calculus core (Φ_U, signature projection) ----------
        self.phi_u_tensor     = nn.Linear(self.vocab_size, self.hidden_dim, bias=False)
        self.signature_matrix = nn.Linear(self.hidden_dim, self.hidden_dim, bias=False)

        # ---- Non-persistent buffers (DDP-safe, checkpoint-excluded) --------
        def _buf(v: float) -> torch.Tensor:
            return torch.tensor(float(v), dtype=torch.float32)

        #   Identity matching the **Gram matrix** dimension L = seq_length.
        #   (The reference used `eye(hidden_dim)` — crashes for L != H.)
        self.register_buffer(
            "_I", torch.eye(self.seq_length, dtype=torch.float32), persistent=False,
        )
        self.register_buffer("_lambda", _buf(reg_lambda), persistent=False)
        scale = float(viability_scale) if viability_scale is not None else float(self.seq_length)
        self.register_buffer("_viability_scale", _buf(scale), persistent=False)

    # ------------------------------------------------------------------ #
    # Differentiable sequence generation                                 #
    # ------------------------------------------------------------------ #
    def _sample_sequence(
        self,
        batch_logits: torch.Tensor,     # [B, L, V]
        temperature: torch.Tensor,      # scalar
        hard: bool,
    ) -> torch.Tensor:
        """
        Differentiable discrete sampler with straight-through gradients.

        Training (or `deterministic_eval=False`):
            Gumbel–Softmax with hard=True → hard forward, soft backward.

        Eval (with `deterministic_eval=True`):
            argmax of softmax(logits/τ) with a straight-through estimator —
            deterministic and reproducible.
        """
        if self.training or not self.deterministic_eval:
            return F.gumbel_softmax(batch_logits, tau=temperature, hard=hard, dim=-1)

        probs = F.softmax(batch_logits / temperature, dim=-1)
        if not hard:
            return probs
        idx = probs.argmax(dim=-1, keepdim=True)
        hard_one_hot = torch.zeros_like(probs).scatter_(-1, idx, 1.0)
        # Straight-through: hard forward, soft backward.
        return hard_one_hot - probs.detach() + probs

    # ------------------------------------------------------------------ #
    # Topological viability via Cholesky log-det                         #
    # ------------------------------------------------------------------ #
    def _compute_viability(self, M_A: torch.Tensor) -> torch.Tensor:
        """
        Per-sample topological viability via the Cholesky log-determinant of
        the SPD matrix  `M_A M_Aᵀ + λ I_L`.

        Parameters
        ----------
        M_A : torch.Tensor  [B, L, H]

        Returns
        -------
        viability : torch.Tensor  [B, 1]  ∈ (0, 1)
        """
        dtype_out = M_A.dtype
        device    = M_A.device

        # Cholesky in fp32 for numerical robustness under AMP.
        M32   = M_A.float()
        I     = self._I.to(device=device)
        lam   = self._lambda.to(device=device)
        scale = self._viability_scale.to(device=device)

        # SPD construction:  M_A M_Aᵀ + λ I_L   →  [B, L, L]
        reg = M32 @ M32.transpose(-2, -1) + lam * I

        # Canonical SPD log-det:  2 · Σ log(diag(L_chol)).
        L_chol = torch.linalg.cholesky(reg)
        log_det = 2.0 * torch.log(
            torch.diagonal(L_chol, dim1=-2, dim2=-1)
        ).sum(dim=-1)                                          # [B]

        # Per-sample viability — mean log-eigenvalue scale.
        viability = torch.sigmoid(log_det / scale)             # [B]
        return viability.to(dtype_out).unsqueeze(-1)           # [B, 1]

    # ------------------------------------------------------------------ #
    # Core step (isolated for gradient checkpointing)                    #
    # ------------------------------------------------------------------ #
    def _step(
        self,
        batch_size: int,
        temperature: torch.Tensor,
        noise_scale: torch.Tensor,
    ) -> Dict[str, torch.Tensor]:

        # ---- 1. Expand logits for the batch — view, no alloc ---------------
        batch_logits = self.seq_logits.expand(batch_size, -1, -1)

        # ---- 2. Gumbel-Softmax sampling with STE ---------------------------
        sampled_seq = self._sample_sequence(batch_logits, temperature, hard=True)

        # ---- 3. Universal Contraction Operator Φ_U -------------------------
        phi_u = self.phi_u_tensor(sampled_seq)                          # [B, L, H]

        # ---- 4. Topological signature matrix -------------------------------
        M_A = self.signature_matrix(phi_u)                              # [B, L, H]

        # ---- 5. Per-sample viability via Cholesky log-det ------------------
        viability_score = self._compute_viability(M_A)                  # [B, 1]

        # ---- 6. Mutation gate — C^∞, per-sample ---------------------------
        mutation_gate = 1.0 - viability_score                           # [B, 1]

        # ---- 7. Disordered noise — training-only ---------------------------
        if self.training:
            disordered_noise = torch.randn_like(sampled_seq) * noise_scale
        else:
            disordered_noise = torch.zeros_like(sampled_seq)
        mutated_seq = sampled_seq + disordered_noise * mutation_gate.unsqueeze(-1)

        # ---- 8. Stochastic homogenization — macroscopic smooth limit ------
        macroscopic_limit = F.softmax(mutated_seq / temperature, dim=-1)

        return {
            "macroscopic_sequence": macroscopic_limit,
            "hard_tokens":          macroscopic_limit.argmax(dim=-1),
            "viability_score":      viability_score,
        }

    # ------------------------------------------------------------------ #
    # Forward                                                            #
    # ------------------------------------------------------------------ #
    def forward(
        self,
        batch_size: int = 1,
        temperature: Union[float, torch.Tensor] = 1.0,
        noise_scale: Union[float, torch.Tensor] = 0.1,
    ) -> Dict[str, torch.Tensor]:
        """
        Returns
        -------
        dict with:
            'macroscopic_sequence' : [B, L, V]  differentiable soft sequence
            'hard_tokens'          : [B, L]     discrete token indices
            'viability_score'      : [B, 1]     ∈ (0, 1), per-sample
        """
        if self.validate_inputs and (not isinstance(batch_size, int) or batch_size <= 0):
            raise ValueError("batch_size must be a positive int.")

        # Promote scalar args to on-device tensors — no Python floats in graph.
        device = self.seq_logits.device
        dtype  = self.seq_logits.dtype
        if not isinstance(temperature, torch.Tensor):
            temperature = torch.tensor(float(temperature), dtype=dtype, device=device)
        if not isinstance(noise_scale, torch.Tensor):
            noise_scale = torch.tensor(float(noise_scale), dtype=dtype, device=device)

        if self.gradient_checkpointing and self.training:
            return torch.utils.checkpoint.checkpoint(
                self._step, batch_size, temperature, noise_scale,
                use_reentrant=False,
            )
        return self._step(batch_size, temperature, noise_scale)


# =============================================================================
# Production execution example
# =============================================================================
if __name__ == "__main__":
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    torch.manual_seed(0)
    print(f"[SESI-Designer v2] Running on: {device}")

    designer = DifferentiableStructuralDesigner(seq_length=200).to(device)
    designer.train()
    optimizer = torch.optim.AdamW(designer.parameters(), lr=1e-3)

    autocast_ctx = (
        torch.amp.autocast(device_type="cuda", dtype=torch.bfloat16)
        if device.type == "cuda" else torch.no_grad()
    )
    optimizer.zero_grad(set_to_none=True)
    with autocast_ctx:
        output = designer(batch_size=32)
        loss = -output["viability_score"].float().mean()

    loss.backward()
    optimizer.step()

    print(f"  Batch loss (structural-collapse penalty): {loss.item():.4f}")
    print(f"  Viability score shape  : {tuple(output['viability_score'].shape)}")
    print(f"  Macroscopic seq shape  : {tuple(output['macroscopic_sequence'].shape)}")
    print(f"  Hard tokens shape      : {tuple(output['hard_tokens'].shape)}")
    print(f"  Sample sequence        : "
          f"{output['hard_tokens'][0][:20].detach().cpu().tolist()}...")

    # Gradient-flow audit
    grad_ok = True
    for name, p in designer.named_parameters():
        if p.grad is None or not torch.isfinite(p.grad).all():
            grad_ok = False
            print(f"  [WARN] non-finite or missing grad: {name}")
    print(f"  Autograd               : "
          f"{'FULLY CONNECTED — C^∞ differentiable' if grad_ok else 'FAILED'}")
